# Generated by Django 5.1.6 on 2025-02-05 18:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=255)),
                ('policy_type', models.CharField(default='', max_length=255)),
                ('expiry_date', models.DateField(default='', validators=[api.models.validate_expiry_date])),
            ],
        ),
    ]
