# Generated by Django 5.1.6 on 2025-02-05 18:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policies',
            name='expiry_date',
            field=models.DateField(validators=[api.models.validate_expiry_date]),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_type',
            field=models.CharField(max_length=255),
        ),
    ]
