# Generated by Django 5.1.6 on 2025-02-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_policies_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policies',
            new_name='Policy',
        ),
    ]
