# Generated by Django 5.1.6 on 2025-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_policies_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('home', 'Home')], max_length=255),
        ),
    ]
